### ISSUE TITLE
Can not decompile nsis x64

### ISSUE THREAD

**Issue by seven1oe** [myfreeer/7z-build-nsis#11]
I used nsis x64(3.06.1) to make a installer and this build(and other versions of 7z) can not decompile it.

**Comment by myfreeer** [comment]
Thid build only enables the `nsis script` featues which is disabled by official version by default, if the nsis package can not be opened by official 7-zip, this build won't open it either.

**Comment by Kein** [comment]
> I used nsis x64(3.06.1) to make a installer and this build(and other versions of 7z) can not decompile it.

Where did yo get "x64 version? I cant find it anywhere, all official builds are x32
