### ISSUE TITLE
Support for Nsis 3.x/2020

### ISSUE THREAD

**Issue by Kein** [myfreeer/7z-build-nsis#12]
Example:
https://download.unity3d.com/download_unity/becced5a802b/Windows64EditorInstaller/UnitySetup64-2020.2.4f1.exe

**Comment by myfreeer** [comment]
Is this packed with [official nsis](https://nsis.sourceforge.io/Download) or some private modified version?

See also https://github.com/myfreeer/7z-build-nsis/issues/11

**Comment by Kein** [comment]
Not modifed but I guess it is #11 
That sucks, oh well.

**Comment by myfreeer** [comment]
Also you can try official 7-zip and [ask](https://sourceforge.net/p/sevenzip/discussion/45797/) for their help.
