### ISSUE TITLE
7-Zip 21.06 incl. Code was released. 

### ISSUE THREAD

**Issue by DARO75** [myfreeer/7z-build-nsis#21]
https://7-zip.org/a/7z2106-src.7z
(с)https://sourceforge.net/p/sevenzip/discussion/45797/thread/b463f34259/?limit=25#ab45

**Comment by myfreeer** [comment]
Thank you for reporting

**Comment by myfreeer** [comment]
https://github.com/myfreeer/7z-build-nsis/releases/tag/21.06
