### ISSUE TITLE
7-Zip 21.07 incl. Code was released.

### ISSUE THREAD

**Issue by DARO75** [myfreeer/7z-build-nsis#22]
https://7-zip.org/a/7z2107-src.7z
(с)https://sourceforge.net/p/sevenzip/discussion/45797/thread/0a7b47970b

**Comment by myfreeer** [comment]
Thank you for noticing.

Dan ***@***.***> 于2021年12月27日周一 23:00写道：

**Comment by myfreeer** [comment]
https://github.com/myfreeer/7z-build-nsis/releases/tag/21.07
