### ISSUE TITLE
23.01 Not Finding/Extracting NSIS (.nsi) files

### ISSUE THREAD

**Issue by Saloframes** [myfreeer/7z-build-nsis#45]
I upgraded to version 23.01 from releases, however, it's not finding/extracting the NSIS file from the same .exe that the previous release did. 

From 22.01:
![old](https://github.com/myfreeer/7z-build-nsis/assets/5899823/60923581-bc20-4503-8262-5d6eba579f9a)

From 23.01:
![new](https://github.com/myfreeer/7z-build-nsis/assets/5899823/ce37f6cc-f770-4e1c-b0cd-0294d0a3684f)

**Comment by myfreeer** [comment]
Thank you for reporting.
Patch updated and you can preview the compiled binary [here](https://ci.appveyor.com/project/myfreeer/7z-build-nsis/builds/47375185/job/5q55a524dn64kcgi/artifacts), the 23.01 release would be deleted and recreated soon after all the ci builds completed.

**Comment by myfreeer** [comment]
Fixed [here](https://github.com/myfreeer/7z-build-nsis/releases/tag/23.01)
