### ISSUE TITLE
7za extra v19.00 x64 doesn't unpack NSIS

### ISSUE THREAD

**Issue by SLDiggie** [myfreeer/7z-build-nsis#5]
> 7za l MyNSIS.exe
> ERROR: MyNSIS.exe : Can not open the file as archive

This is with NSIS installers that 7zFM will handle.

**Comment by myfreeer** [comment]
> 7za.exe (a = alone) is a standalone version of 7-Zip. 7za.exe supports **only 7z, xz, lzma, cab, zip, gzip, bzip2 and tar formats**. 7za.exe doesn't use external modules.

From the `7-zip.chm` file.

**Comment by myfreeer** [comment]
Also, check for output in `7za i`
